{% set name = "geotext" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ba5aa03db8246a8f77f9a334e79bc1f5875b38fd63589f0be4c83c1d94c52fd

build:
  #noarch: python
  skip: True  # [win]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - geotext

about:
  home: https://pypi.org/project/geotext/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Geotext extracts country and city mentions from text'
  description: |
    Geotext extracts country and city mentions from text
  doc_url: https://geotext.readthedocs.io/en/ 
  dev_url: https://github.com/elyase/geotext

extra:
  recipe-maintainers:
    - CurtLH 
