travis:
  secure:
    BINSTAR_TOKEN: VuFnZAmTMuzwLJ63LWbywYRof1cmP42lVgpmQ6kBxMGGkj8umnc3/CJxsdxoZbTJOZ0XF9TNjqdS9GK4LyAa1nMO9bt5rESSs7IwpM68pPCJSjd7mkL6WwnNCbRHzMzC5hU1BEjMpBul14zta5YAxhNUX8C83yJFQE6SJS4hDXhoEgjWxDbAb5SY7e1AKeEEB2i4QSATQorAX2VMRsWze40Oqytxd7PxX201KiAqAjwabpB7yCI6AjbjhdpwzEUBRGhki8HyD00xlVOizFhTwAjI/yROIpnRrzcHRFxZ6czUUsa7nEkTdSYTxSG8bG3FBBj313S3PqQFHAbc2zZIER9pHbLH1l0y7U4CC7PMsHDpQq3pt7RifixiyZ3rQ6ePNwrKBcWzeiUtAwoB/Hp3Ea14Jv0Q8qKZMRpa2uk/zWV5yG3xo7ddz3F7z02Peh1lDrAiWsHMzmE6UNoHVlB1fLQnXt50kPQ0j191gDfb8mItm9qPRX49q6tFYxwKuvj/+4NF3B6ZREgN+KKtvbwg1qQUYA1xL9PZAy2ai6tbJ/9EGgSuoCi28dhynLhslMPTGma7owJnFFWWHQzBuopAiosbJVEF63I1u0Wkd6PJ1uWfjM1vtnlbQgJQxnaUgH9smoP1LFdhca138A9R4huXIV4LLUXrswsh6adg1C2Smvo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
