travis:
  secure:
    BINSTAR_TOKEN: UIByi4Zuozi/rtaFzAQZtsJPcK4jDMIdaSJ1veLH30qPQt5yV3vAwlFLrRUlrWxBTDIIXRufhupnE/ZQJS//xwwq/bXWW+Irn/hQXih/LNFMmugbtEZjccI8+O94yxda9yMXpNcDPnkDb6zYBSW2r4bs6UlTlJfNCTThPVuSEQDKOpN+S1o/cU8TnlLR+UVhiZ+N+neSxqyqlLUm2Rezu4dDpKzMWjmQVE0U5SAWowkdNGvzyGgkMio1g7SKEVw6TdJOTfVKu3iakp1PaHKMd4iCfm5TmAUYgH8uAem0u/bbrhzjSqkUwhQJLHPij/oVWDjnl2h3g6iQdcF+jiR9WKFMCnb11uEsIPp+tvwZvFtPSlbC871wzM+I6om2XGlMH5cDeSk/W2MPYfQmNFw4ivAg4CXIhlLQN5e7qtI5KoHrNUQKBWg+tyPG5sfOcC0NjxCAkuDr3QeoWPWGXkh07m4Cl9tcpeDoZgmiTTglNzQnWLEHgLB6B46Y5bv1CGM/juARpyzMPcVTNlK4HKubFDmvmHp1aFz2C89ylN6VevXkTYWJkTiDB2DQBRc3V08Nji4SXbiUR//BaVSiNP8/iaW15HYG7HeDuze4va2Mhztof53vbMWePbs1Te2OekNko5UUFtnGoDoCw9IA0VQV6+S4ye2661glYMfINPTH1/c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
