travis:
  secure:
    BINSTAR_TOKEN: a6BN+tIhgAnZdVfAQtj2V3w7CMkF7nl9CfLeoFSNhm14wlVnYe/O4ClPJxQ65dVDdxoNjLNN14FwTKU1zQxoh/gGsD48fX+uqTO9T2i7nvnp38hthZceuhkM2AGNi4GarDdPHURw+Pt5l37PvosPZERyLYAsB4SO4zctYJhhLJhzbZMIe1FbSUUkVmxgLuBGMgrKN5+nfQeTKQ/lrqRcZJy9GbrgBZb7Iue3AhwJ5c5ian7HM/piIF5PeVhyg8J2u1OFZZtFP8hfXIgMgO8OSsPzTpsx5b5HJCqKS1yDhYGcaBpgWtzFZZw3SIlcGIDXOtybguxMpl3elhHF2UqTW+wFH+WycASr+I/F5E/9upgseCnkUb9ojZJ4kbfRRrCLlXvUy+Ws+FKCtSYZQETbZD8P6cBXNiJKAVtnKSkMJgyj0wduJfXVxr1R+KCcNSgipIUanYa5updRsjzBJGO+R/PY75xHgCkTzfG7At0j1xFgzx40ED8PrLE6Ahi18iZbcseDV5p1IYRYm5DETeCiGZq9rYmoIF8vkWHpED5AixJQiGeAPvq0gCW0InPbU4VVhxJzUiv6b4XWNcVpE0X9lGWh4c2/VDw2RMX/u/scdVrinnqULt1LTzWH1pAZaEGVC6uY3y3lW0ydyTPPxSg30wTGzcSAL1iXNIqDVK9H1nc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
